CREATE TABLE Nguoi (
    MaNguoi INT AUTO_INCREMENT PRIMARY KEY,
    HoTen VARCHAR(50) NOT NULL,
    NgaySinh DATE NOT NULL,
    DiaChi VARCHAR(100) NOT NULL,
    Sdt CHAR(10) NULL
);

CREATE TABLE TaiKhoan (
    TaiKhoan VARCHAR(50) PRIMARY KEY,
    MatKhau VARCHAR(50) NOT NULL,
    LoaiTK CHAR(1) NOT NULL
);

CREATE TABLE TheThuVien (
    MaTTV VARCHAR(50) PRIMARY KEY,
    ThoiHan DATE NOT NULL
);

CREATE TABLE Admin (
    MaNguoi INT,
    TaiKhoan VARCHAR(50),
    PRIMARY KEY (MaNguoi, TaiKhoan),
    FOREIGN KEY (MaNguoi) REFERENCES Nguoi(MaNguoi),
    FOREIGN KEY (TaiKhoan) REFERENCES TaiKhoan(TaiKhoan)
);

CREATE TABLE DocGia (
	MaDG INT AUTO_INCREMENT PRIMARY KEY,
	MaNguoi INT,
	MaTTV VARCHAR(50),
	LoaiDG INT,
	FOREIGN KEY (MaNguoi) REFERENCES Nguoi(MaNguoi),
    FOREIGN KEY (MaTTV) REFERENCES TheThuVien(MaTTV)
);

CREATE TABLE NhanVien (
    MaNV INT AUTO_INCREMENT PRIMARY KEY,
    MaNguoi INT,
    TaiKhoan VARCHAR(50),
    FOREIGN KEY (MaNguoi) REFERENCES Nguoi(MaNguoi),
    FOREIGN KEY (TaiKhoan) REFERENCES TaiKhoan(TaiKhoan)
);
CREATE TABLE TheLoai (
    MaTL INT AUTO_INCREMENT PRIMARY KEY,
    TenTL VARCHAR(50) NOT NULL
);


CREATE TABLE DauSach (
    MaDS INT AUTO_INCREMENT PRIMARY KEY,
    TenDS VARCHAR(255) NOT NULL,
    TenSach VARCHAR(50) NOT NULL,
    TenTG VARCHAR(50) NOT NULL,
    SoLuong INT NOT NULL,
    MaNS INT,
    CONSTRAINT MaNS_FK FOREIGN KEY (MaNS) REFERENCES TheLoai(MaTL)
);

CREATE TABLE Sach (
    MaSach VARCHAR(50) PRIMARY KEY,
    MaDS INT,
    TrangThai INT NOT NULL,
    CONSTRAINT MaDS_FK FOREIGN KEY (MaDS) REFERENCES DauSach(MaDS)
);

CREATE TABLE PhieuMuon (
    MaPM INT AUTO_INCREMENT PRIMARY KEY,
    MaTTV VARCHAR(50),
    MaNV INT,
    NgayMuon DATE NOT NULL,
    NgayTra DATE NOT NULL,
    LuaChon VARCHAR(50) NOT NULL,
    TrangThai VARCHAR(20) NOT NULL,
    CONSTRAINT MaTTV_FK4 FOREIGN KEY (MaTTV) REFERENCES TheThuVien(MaTTV),
    CONSTRAINT MaNV_FK FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
);

CREATE TABLE ChiTietPhieuMuon (
    MaPM INT,
    MaSach VARCHAR(50),
    CONSTRAINT MaPM_PK PRIMARY KEY (MaPM, MaSach),
    CONSTRAINT MaPM_FK FOREIGN KEY (MaPM) REFERENCES PhieuMuon(MaPM),
    CONSTRAINT MaSach_FK FOREIGN KEY (MaSach) REFERENCES Sach(MaSach)
);

CREATE TABLE PhieuPhat (
    MaPP INT PRIMARY KEY,
    MaPM INT,
    LyDo VARCHAR(255) NOT NULL,
    CONSTRAINT MaPM_FK1 FOREIGN KEY (MaPM) REFERENCES PhieuMuon(MaPM)
);

INSERT INTO `nguoi` (`MaNguoi`, `HoTen`, `NgaySinh`, `DiaChi`, `Sdt`) VALUES (NULL, 'Nguyễn Văn A', '2003-03-19', 'Đào Xá, Thanh Thủy, Phú Thọ', '0394514319');
INSERT INTO `taikhoan` (`TaiKhoan`, `MatKhau`, `LoaiTK`) VALUES ('admin', '123456', '0');
INSERT INTO `admin` (`MaNguoi`, `TaiKhoan`) VALUES ('1', 'admin');
